### ISSUE TITLE
slow to slice and wont export

### ISSUE THREAD

**Issue by onsitespouting** [stewartoallen/gridspace-wiki#5]
Have upgraded to 8 gigs ram,still won't export?

**Comment by stewartoallen** [comment]
I believe recent changes have improved this for you?

**Comment by onsitespouting** [comment]
Hi Stewart, yes,it has made a huge difference,  I think I sliced a 58 mb
part, it was slow but it worked, it printed in solid, also pause is working
since you added the printer to the slicer.
Let me know if you want anything tested
Mark

**Comment by stewartoallen** [comment]
I'll continue to make memory improvements over time.  glad this is working for you now.
