### ISSUE TITLE
Sliced laser output has ~3.3 times smaller dimensions

### ISSUE THREAD

**Issue by dandumit** [stewartoallen/gridspace-wiki#6]
Nice application.
I have tried it for some stl files and output svg slices are scaled down .
Am I doing something wrong ?

Please see example files. First one gives dimensions that it should have and the last one it's the STL file.

![motor mount draw](https://cloud.githubusercontent.com/assets/670552/18517816/49a20aec-7aa6-11e6-8c7c-b5b9b08a045f.jpg)
[motor-mount-plate-nema-17-stepper-moto.zip](https://github.com/stewartoallen/gridspace-wiki/files/472389/motor-mount-plate-nema-17-stepper-moto.zip)

Output dimensions are about 3.3 times smaller.

I have tried to submit an issue but it seems that I'm not allowed.

BR,
Daniel

**Comment by stewartoallen** [comment]
Just pushed a new version that should fix this.  Please close the issue if verified.

**Comment by dandumit** [comment]
Now it's working correctly !!
Thank you.
